### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by deviprsd** [alexanderldavis/Voleter#1]
You could possibly create a central system, but instead of sending instructions directly to local app in the system, I highly recommend using Spotify Connect Web Api's. That way you will be able to use gestures and control all the possible devices linked to an account. https://developer.spotify.com/documentation/web-api/guides/using-connect-web-api/

**Comment by alexanderldavis** [comment]
Thanks for the suggestion! I will look into it, I hadn't considered the Spotify API, but that does seem like a more portable solution!
